name: myfuneral
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  fluttertoast: ^8.1.1
  connectivity: ^3.0.6
  easy_splash_screen: ^1.0.4
  cloud_firestore: ^4.0.2
  flutter_redux: ^0.10.0
  redux: ^5.0.0
  flutter_redux_dev_tools: ^0.5.2
  redux_thunk: ^0.4.0
  http: ^0.13.5
#  intl: ^0.17.0
  adaptive_navbar: ^0.0.3
  awesome_snackbar_content: ^0.0.9
#  dropdown_search: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

