// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnMgGctw6egGT9wy-mBOqu3-ew9isMuSE',
    appId: '1:1099318727978:web:307535b0b162802e197a53',
    messagingSenderId: '1099318727978',
    projectId: 'myfuneralplan-77b55',
    authDomain: 'myfuneralplan-77b55.firebaseapp.com',
    databaseURL: 'https://myfuneralplan-77b55-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myfuneralplan-77b55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSp-aW8_8dukcioxt3EdLW_64GU5WPjF8',
    appId: '1:1099318727978:android:b13edb732eff2d02197a53',
    messagingSenderId: '1099318727978',
    projectId: 'myfuneralplan-77b55',
    databaseURL: 'https://myfuneralplan-77b55-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myfuneralplan-77b55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJgxqNA9IOF6l2GfY6oLrLKWv8jo7Zquk',
    appId: '1:1099318727978:ios:cc0597cd2922eb35197a53',
    messagingSenderId: '1099318727978',
    projectId: 'myfuneralplan-77b55',
    databaseURL: 'https://myfuneralplan-77b55-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myfuneralplan-77b55.appspot.com',
    androidClientId: '1099318727978-h0t96hqi1l8c5f213l1siq7iul7bauak.apps.googleusercontent.com',
    iosClientId: '1099318727978-m4j9mvr7l1qrn0qmrqsk20jr0qq9df3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfuneral',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJgxqNA9IOF6l2GfY6oLrLKWv8jo7Zquk',
    appId: '1:1099318727978:ios:cc0597cd2922eb35197a53',
    messagingSenderId: '1099318727978',
    projectId: 'myfuneralplan-77b55',
    databaseURL: 'https://myfuneralplan-77b55-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'myfuneralplan-77b55.appspot.com',
    androidClientId: '1099318727978-h0t96hqi1l8c5f213l1siq7iul7bauak.apps.googleusercontent.com',
    iosClientId: '1099318727978-m4j9mvr7l1qrn0qmrqsk20jr0qq9df3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.myfuneral',
  );
}
